import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE,
} from '@/constants/navigation.constant'

import type { NavigationTree } from '@/@types/navigation'

const navigationConfig: NavigationTree[] = [
    {
        key: 'dashboard',
        path: '/dashboard',
        title: 'Dashboard',
        icon: 'home',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    /** Example purpose only, please remove */
	{
        key: 'inventory',
        path: '',
        title: 'Inventarisasi',
        icon: '',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [],
        subMenu: [
            {
                key: 'inventory.facility',
                path: '/facility',
                title: 'Fasilitas',
                icon: 'facility',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
			{
                key: 'inventory.bus',
                path: '/bus',
                title: 'Bus',
                icon: 'bus',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
			{
                key: 'inventory.halte',
                path: '/halte',
                title: 'Halte',
                icon: 'halte',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            
        ],
    },
	// {
    //     key: 'inventarisasi',
    //     path: '',
    //     title: 'Inventarisasi',
    //     icon: 'inventory',
    //     type: NAV_ITEM_TYPE_COLLAPSE,
    //     authority: [],
    //     subMenu: [
    //         {
    //             key: 'inventarisasi.facility',
    //             path: '/facility',
    //             title: 'Fasilitas',
    //             icon: '',
    //             type: NAV_ITEM_TYPE_ITEM,
    //             authority: [],
    //             subMenu: [],
    //         },
    //         {
    //             key: 'inventarisasi.bus',
    //             path: '/bus',
    //             title: 'Bus',
    //             icon: '',
    //             type: NAV_ITEM_TYPE_ITEM,
    //             authority: [],
    //             subMenu: [],
    //         },
    //         {
    //             key: 'inventarisasi.halte',
    //             path: '/halte',
    //             title: 'Halte',
    //             icon: '',
    //             type: NAV_ITEM_TYPE_ITEM,
    //             authority: [],
    //             subMenu: [],
    //         },
    //     ],
    // },
    // {
    //     key: 'transaction',
    //     path: '',
    //     title: 'Transaksi',
    //     icon: 'transaction',
    //     type: NAV_ITEM_TYPE_COLLAPSE,
    //     authority: [],
    //     subMenu: [
    //         {
    //             key: 'transaction.loan',
    //             path: '/loan',
    //             title: 'Peminjaman',
    //             icon: '',
    //             type: NAV_ITEM_TYPE_ITEM,
    //             authority: [],
    //             subMenu: [],
    //         },
    //         {
    //             key: 'transaction.maintenance',
    //             path: '/maintenance',
    //             title: 'Perawatan',
    //             icon: '',
    //             type: NAV_ITEM_TYPE_ITEM,
    //             authority: [],
    //             subMenu: [],
    //         },
    //         {
    //             key: 'transaction.procurement',
    //             path: '/procurement',
    //             title: 'Pengadaan',
    //             icon: '',
    //             type: NAV_ITEM_TYPE_ITEM,
    //             authority: [],
    //             subMenu: [],
    //         },
    //         {
    //             key: 'transaction.disposal',
    //             path: '/disposal',
    //             title: 'Penghapusan',
    //             icon: '',
    //             type: NAV_ITEM_TYPE_ITEM,
    //             authority: [],
    //             subMenu: [],
    //         },
    //     ],
    // },
    {
        key: 'master',
        path: '',
        title: 'Master Data',
        icon: '',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [],
        subMenu: [
            {
                key: 'master.category',
                path: '/category',
                title: 'Kategori',
                icon: 'master',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'master.track',
                path: '/track',
                title: 'Rute Trayek',
                icon: 'track',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'master.user',
                path: '/user',
                title: 'User',
                icon: 'user',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
	{
        key: 'guide',
        path: '',
        title: 'Guide',
        icon: 'guide',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [],
        subMenu: [
            {
                key: 'guide.documentation',
                path: '/documentation',
                title: 'Documentation',
                icon: 'documentation',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            
        ],
    },
]

export default navigationConfig
